### ISSUE TITLE
关于目录名-->专辑名格式化的问题，以及搜索只有一个结果但不自动选用的问题

### ISSUE THREAD

**Issue by maiwulan6** [the1812/Touhou-Tagger#4]
老板您好，十分感谢您的这个工具，对我用处很大，但是目前发现有两个问题，希望老板能帮忙解决下，会十分感激您。谢谢。
ps：我没有能力进行修改，但是还是尝试对程序进行了一些修改，但是没有达到我预期的目的。
1、tlmc合集目录名为"2009.12.30 少女酩酊中 [C77]"类似这种格式，工具无法自动识别其中专辑名，我尝试加了替换：
        var newAlbumName = albumName.replace(/\d{4}\.\d{2}\.\d{2} */,"");
        var newAlbumName = newAlbumName.replace(/\[[A-Z]*-[0-9]*\] */,"");
        var newAlbumName = newAlbumName.replace(/ *\[[^\x00-\xff]*[A-Z]*[0-9]*\]/,"");
但是我修改完后无法正常运行，希望您修改下工具使得在搜索thwiki前对专辑名进行格式化。
2、工具添加-I选项后无法自动选择第一个匹配的搜索项作为专辑信息进行下载，能否加个强制选择第一个搜索项作为下载项的选项。
十分感谢。

**Comment by the1812** [comment]
更新到 v1.2.1 就可以了
