### ISSUE TITLE
批量运行时TLMC格式专辑名提取失败

### ISSUE THREAD

**Issue by cicur** [the1812/Touhou-Tagger#5]
如下图，在单个文件夹内可以正常提取
![image](https://user-images.githubusercontent.com/88472780/158934344-685ab4f7-6829-4909-a6cd-4bde002301e6.png)

另：能否支持多层文件夹的批量运行，就是TLMC的目录结构
类似这样

```
L:.
├─[Foxtail-Grass Studio]
│  ├─2010.12.30 [FGST-0001] Lupinus 幻想写景 -風- [C79]
│  ├─2011.02.20 [FGST-0002] Remember＊C -spring- [科学世紀のカフェテラス]
│  ├─2011.08.13 [FGST-0003] Remember＊C -summer- [C80]
│  ├─2011.10.16 [FGST-0004] Remember＊C -autumn- [東方紅楼夢7]
│  ├─2011.12.30 [FGST-0005] Cattleya 幻想写景 -妖- [C81]
│  ├─2011.12.30 [FGST-0006] Remember＊C -winter- [C81]
│  ├─2012.05.27 [FGST-0007] Re＊Circulation [例大祭9]
│  ├─2012.08.11 [FGST-0008] なつかぜメモリア [C82]
│  ├─2012.12.30 [FGST-0009] つきかげクオリア [C83]
│  ├─2013.05.26 [FGST-0010] ときかけエオリア [例大祭10]
│  ├─2013.08.12 [FGST-0011] monocolotion [C84]
│  ├─2014.12.29 [FGST-0012] ほしくずアテリア [C87]
│  │  └─BK
│  ├─2015.05.10 [FGST-0013] ゆきどけアゼリア [例大祭12]
│  └─2015.12.30 [FGST-0014] Re＊Collection [C89]
├─[Sensitive Heart]
│  └─2006.05.21 [SHAC-0004] Scarlet Destiny [例大祭3]
├─[上海アリス幻樂団 & 黄昏フロンティア] ZUN & Twilight frontier
│  ├─2005.08.14 [TFM-001] 幻想曲抜萃 東方萃夢想 ORIGINAL SOUND TRACK [C68]
│  │  ├─01 DAY DISC
│  │  └─02 NIGHT DISC
│  ├─2008.08.16 [TFM-003] 全人類ノ天楽録 東方緋想天 ORIGINAL SOUND TRACK [C74]
│  │  ├─ARRANGE DISC
│  │  └─ORIGINAL DISC
│  ├─2009.12.30 [TFM-004] 核熱造神ヒソウテンソク 東方非想天則 ORIGINAL SOUND TRACK [C77]
│  └─2013.08.12 [TFM-006] 暗黒能楽集・心綺楼　東方心綺楼 ORIGINAL SOUND TRACK [C84]
│      ├─暗黒能楽集・心綺楼　東方心綺楼 ORIGINAL SOUND TRACK Disc1
│      └─暗黒能楽集・心綺楼　東方心綺楼 ORIGINAL SOUND TRACK Disc2
```

非常感谢！

**Comment by cicur** [comment]
在写入[辿／誘](https://thwiki.cc/%E8%BE%BF%EF%BC%8F%E8%AA%98)这张专时也出现了问题
下面是`辿／誘`的`Disc 2 誘`
运行前：
![image](https://user-images.githubusercontent.com/88472780/159009482-d19142b6-8e1a-4bc2-a8a4-7fb51e4502b6.png)
运行后：
![image](https://user-images.githubusercontent.com/88472780/159009532-125f6bd3-61d8-4f4d-b355-d1fc4cc9ff22.png)
可以看出程序写入的是本专辑中`Disc 1 辿`的曲目信息

**Comment by the1812** [comment]
对于多 CD 的专辑, 需要在 CD 的整体目录中运行, 而不是具体的某个 Disc 中
Disc 文件夹的命名必须以 `Disc n` 形式开头, 可以有其他后缀, 例如 `Disc 1` 和 `Disc 1 辿` 都算有效的名称.

![image](https://user-images.githubusercontent.com/26504152/159628584-c0cf4ef5-657c-4501-97df-61228bbe6948.png)
![image](https://user-images.githubusercontent.com/26504152/159628656-2cabdb9f-66fc-429e-af75-0ca4fa961ae2.png)

**Comment by cicur** [comment]
> 对于多 CD 的专辑, 需要在 CD 的整体目录中运行, 而不是具体的某个 Disc 中
> 
> Disc 文件夹的命名必须以 `Disc n` 形式开头, 可以有其他后缀, 例如 `Disc 1` 和 `Disc 1 辿` 都算有效的名称.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/26504152/159628584-c0cf4ef5-657c-4501-97df-61228bbe6948.png)
> 
> ![image](https://user-images.githubusercontent.com/26504152/159628656-2cabdb9f-66fc-429e-af75-0ca4fa961ae2.png)
> 
> 

好的，谢谢

顺带问一下，官方专辑是不支持吗

**Comment by the1812** [comment]
不支持, 只能用于一部分二次同人专辑

**Comment by the1812** [comment]
[v1.3.0](https://github.com/the1812/Touhou-Tagger/releases/tag/v1.3.0) 已更新了批量模式下对文件夹层级的支持, TLMC 这种设为 2 就可以了.

**Comment by cicur** [comment]
感谢
