### ISSUE TITLE
处理大量专辑时内存占用会超过NodeJS的内存限制

### ISSUE THREAD

**Issue by SirnoChan** [the1812/Touhou-Tagger#7]
Windows下运行。设定为歌词下载并批量处理，内存用量会狂飙到超出NodeJS的内存限制。把环境变量改成`NODE_OPTIONS="--max-old-space-size=8192"`，给掉8G内存，只能处理一千个左右的专辑。不清楚是不是歌词下载还没做好的缘故。

另外，目前的no-interactive选项失效了，相关的更改是在 f3ae9b3c2a4eb38e8107d88f7e29d79e884fc63e 中做出的。

**Comment by the1812** [comment]
https://github.com/the1812/Touhou-Tagger/releases/tag/v1.4.1
